services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/bi_ufcg_db
      - DATABASE_USERNAME=bi_user
      - DATABASE_PASSWORD=admin
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bi_ufcg_db
      POSTGRES_USER: bi_user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
